"""Update Worksheet model with new attributes

Revision ID: 1b7c0981b172
Revises: c6ac484d97e4
Create Date: 2024-10-19 16:10:25.003662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7c0981b172'
down_revision = 'c6ac484d97e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtopic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimated_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('learning_objectives', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheet', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('keywords')
        batch_op.drop_column('learning_objectives')
        batch_op.drop_column('estimated_time')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('subtopic')

    # ### end Alembic commands ###
