"""Add is_shared and shared_with columns to Worksheet

Revision ID: c93a748999ff
Revises: 
Create Date: 2024-10-19 02:59:22.345000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93a748999ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shared_with', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheet', schema=None) as batch_op:
        batch_op.drop_column('shared_with')
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###
